### ISSUE TITLE
Build broken for node version 6

### ISSUE THREAD

**Issue by cseale** [ciscospark/react-ciscospark#430]
When building on a node v6 -

```
$ npm run build:all

> alto-react-ciscospark@0.6.0 build:all /react-ciscospark
> cross-env NODE_ENV=${NODE_ENV:-production} npm run build all


> alto-react-ciscospark@0.6.0 build /react-ciscospark
> ./scripts/build/index.js "all"

Cleaning react-component-activity-item es folder...
Transpiling react-component-activity-item to ES5 with import/export ...
/react-ciscospark/node_modules/babel-plugin-transform-postcss/dist/postcss-server.js:56
const main = async function main(socketPath, tmpPath) {
                   ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/react-ciscospark/node_modules/babel-plugin-transform-postcss/dist/postcss-client.js:19
const communicate = async function communicate(socketPath, message) {
                          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/react-ciscospark/node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: Error transpiling /react-ciscospark/packages/node_modules/@ciscospark/react-component-activity-item/src/index.js package, Error: /react-ciscospark/packages/node_modules/@ciscospark/react-component-activity-item/src/index.js: Command failed: node /react-ciscospark/node_modules/babel-plugin-transform-postcss/dist/postcss-client.js /tmp/bptp-userscolmsealealtoreposaltoreactciscospark.sock {"cssFile":"/react-ciscospark/packages/node_modules/@ciscospark/react-component-activity-item/src/styles.css"}
/react-ciscospark/node_modules/babel-plugin-transform-postcss/dist/postcss-client.js:19
const communicate = async function communicate(socketPath, message) {
                          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

    at babelBuild (/react-ciscospark/scripts/utils/build.js:130:6)
    at /react-ciscospark/scripts/utils/build.js:139:8
    at Array.forEach (native)
    at babelBuild (/react-ciscospark/scripts/utils/build.js:136:7)
    at buildES (/react-ciscospark/scripts/utils/build.js:82:2)
    at transpile (/react-ciscospark/scripts/utils/build.js:96:2)
    at /react-ciscospark/scripts/build/commands/all.js:25:7
    at Array.forEach (native)
    at Object.handler (/react-ciscospark/scripts/build/commands/all.js:16:11)
    at Object.self.runCommand (/react-ciscospark/node_modules/yargs/lib/command.js:233:22)
````

This issue is fixed by this GreenKeeper PR: 
https://github.com/ciscospark/react-ciscospark/pull/398

**Comment by adamweeks** [comment]
This has been fixed in #473 via #483
